package hello

import "testing"

// This function is generated by go extension, we just have to fill in test cases.
func TestPrintHello(t *testing.T) {
	type args struct {
		name string
	}
	tests := []struct {
		name string
		args args
		want bool
	}{
		{
			name: "say hello to moruowait",
			args: args{
				name: "moruowait",
			},
			want: true,
		},
		// Add other test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := PrintHello(tt.args.name); got != tt.want {
				t.Errorf("PrintHello() = %v, want %v", got, tt.want)
			}
		})
	}
}
